{% set name = "glasflow" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/glasflow-{{ version }}.tar.gz
  sha256: 53ab35a763b7e198be430e55a50efb6477abd82d260748c404bf70eee0aad9e6 

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools >=64.0.3
    - setuptools-scm
  run:
    - numpy
    - python >=3.7
    - pytorch >=1.11.0

test:
  requires:
    - pip
    - pytest >=6.0.0
    - pytest-rerunfailures
  imports:
    - glasflow
  source_files:
    - tests
    - pyproject.toml
  commands:
    - pip check
    - python -m pytest tests/ -vv

about:
  home: https://github.com/igr-ml/glasflow
  summary: Normalising flows using nflows
  description: | 
    glasflow is a Python library containing a collection of normalising flows
    implemented using PyTorch and nflows.
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  dev_url: https://github.com/igr-ml/glasflow

extra:
  recipe-maintainers:
    - johnveitch
    - mj-will
